version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "20:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: xlsxwriter
    versions:
    - 1.3.8
    - 1.3.9
  - dependency-name: sphinx
    versions:
    - 3.5.2
    - 3.5.3
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: tqdm
    versions:
    - 4.56.2
    - 4.57.0
    - 4.59.0
  - dependency-name: pandas
    versions:
    - 1.2.3
  - dependency-name: watchdog
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: pip
    versions:
    - "21.0"
  - dependency-name: tox
    versions:
    - 3.21.3
