environment:
  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_env.cmd"

  matrix:
    - TOXENV: 'py35'
      MINICONDA: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      
    - TOXENV: 'py36'
      MINICONDA: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      
    - TOXENV: 'py37'
      MINICONDA: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"

build: false  # Not a C# project, build stuff at the test step instead.

before_test:
  - "%CMD_IN_ENV% conda config --add channels conda-forge"
  - "%CMD_IN_ENV% pip install -r requirements_dev.txt"

test_script:
  - "%CMD_IN_ENV% tox -e %TOX_ENV%"
