matrix:
  fast_finish: true

environment:
  matrix:
    - TOXENV: 'py35'
      MINICONDA: "C:\\Miniconda35-x64"
      PLATFORM: x64
      PYTHON_VERSION: "3.5"
      
    - TOXENV: 'py36'
      MINICONDA: "C:\\Miniconda36-x64"
      PLATFORM: x64
      PYTHON_VERSION: "3.6"
      
    - TOXENV: 'py37'
      MINICONDA: "C:\\Miniconda37-x64"
      PLATFORM: x64
      PYTHON_VERSION: "3.7"

build: false

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set show_channel_urls true --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda info -a
  - "conda create --quiet --name test-environment python=%PYTHON_VERSION% pandas --file requirements_dev.txt"

test_script:
  - activate test-environment
  - "%CMD_IN_ENV% tox"
