matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:

  matrix:
    - TOXENV: 'py38'
      MINICONDA: "C:\\Miniconda38-x64"
      PYTHON_VERSION: "3.8"

# all our python builds have to happen in tests_script...
build: false

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
    # set up environment
    - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"
    - conda config --set always_yes yes
    - conda update -q conda
    - conda create -n test-env python=%PYTHON_VERSION%
    - activate test-env
    - conda install shapely --channel=conda-forge
    - conda install -c plotly plotly-orca psutil
    - conda install -c free msvc_runtime
    - python.exe -m pip install --upgrade pip
    - python.exe -m pip install -U flake8
    - python.exe -m pip install --ignore-installed psutil
    - python.exe -m pip install -r requirements_dev.txt

test_script:
    - python.exe -m flake8 pydnameth
    - python.exe -m flake8 tests
    - python.exe setup.py test
